import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def generate_industry_count_df(industry_count, SW_SECTOR_LEVEL_1_List, ETF_DATA_PATH):
    # original industry_count is like {"YYYYMMDD": {"industry_first_class1": count, "industry_first_class2": count, ...}, ...}
    # Turn it into a DataFrame for easier plotting
    # The industry order is based on the order in SW_SECTOR_LEVEL_1_List
    # Empty dates will be filled with 0 counts for all industries

    # 1. Pass keys and values explicitly so empty dicts are kept as rows
    industry_count_df = pd.DataFrame(list(industry_count.values()), index=list(industry_count.keys()))

    # 2. Reindex columns to match SW_SECTOR_LEVEL_1_List order and fill missing industries with 0
    industry_count_df = industry_count_df.reindex(columns=SW_SECTOR_LEVEL_1_List, fill_value=0)

    # 3. Fill the NaNs generated by the empty dictionary dates ({}) with 0
    industry_count_df = industry_count_df.fillna(0)

    # 4. Convert the string index ("YYYYMMDD") to datetime format
    industry_count_df.index = pd.to_datetime(industry_count_df.index, format='%Y%m%d')

    # 5. Fill in completely missing calendar dates in the time series sequence with 0
    if not industry_count_df.empty:
        full_date_range = pd.date_range(start=industry_count_df.index.min(), end=industry_count_df.index.max(), freq='D')
        industry_count_df = industry_count_df.reindex(full_date_range, fill_value=0)

    # 6. Convert the datetime index into a dedicated column named "date"
    industry_count_df = industry_count_df.reset_index().rename(columns={'index': 'date'})
    # 7. Set the "date" column as the index of the DataFrame
    industry_count_df.set_index("date", inplace=True)

    # save industry_count_df to CSV for future analysis
    industry_count_df.to_csv(ETF_DATA_PATH + "AD_Industry_Count_Analysis.csv", index=True, encoding='utf-8')
    
    return industry_count_df

def calculate_asset_metrics(file_name, etf_data_path, begin_date, end_date, trading_days):
    """Reads a single file once and returns ROI and PnL series aligned strictly to trading days."""
    
    # Read and parse dates directly as datetime64 objects
    df = pd.read_csv(etf_data_path + file_name, parse_dates=['date'])
    
    # Filter using fast datetime boolean indexing
    df_filtered = df[(df['date'] >= begin_date) & (df['date'] <= end_date)].sort_values('date').reset_index(drop=True)
    
    if df_filtered.empty:
        return pd.Series(0.0, index=trading_days), pd.Series(1.0, index=trading_days)
        
    # Calculate daily ROI across available trading days
    roi_series = df_filtered['close'].pct_change()
    # Explicit override for day 1 entry boundary
    roi_series.iloc[0] = (df_filtered.loc[0, 'close'] - df_filtered.loc[0, 'open']) / df_filtered.loc[0, 'open']
    
    # Map back to index and reindex strictly to the true TRADING DAYS
    # If an asset is suspended on a trading day, it fills with 0.0 ROI
    temp_df = pd.DataFrame({'ROI': roi_series.values}, index=df_filtered['date'])
    temp_df = temp_df.reindex(trading_days, fill_value=0.0)
    
    # Compute cumulative performance (PnL)
    temp_df['PnL'] = (1 + temp_df['ROI']).cumprod()
    
    return temp_df['ROI'], temp_df['PnL']

def calculate_industry_and_benchmark_metrics(
    ETF_DATA_PATH, SW_SECTOR_LEVEL_1_List, 
    SW_SECTOR_PATH_MAPPING, BENCHMARK_List, 
    BENCHMARK_PATH_MAPPING, start_dt, end_dt, 
    trading_days
):
    """
    Calculate ROI and PnL for all industries and benchmarks in a single pass.
    Returns:
        industry_level1_roi_all_df: DataFrame of ROI for all industries
        industry_level1_pnl_all_df: DataFrame of PnL for all industries
        benchmark_roi_all_df: DataFrame of ROI for all benchmarks
        benchmark_pnl_all_df: DataFrame of PnL for all benchmarks
    """
    output = {}
    ind_roi_pool = {}
    ind_pnl_pool = {}

    for industry in SW_SECTOR_LEVEL_1_List:
        file_name = SW_SECTOR_PATH_MAPPING[industry]
        roi, pnl = calculate_asset_metrics(file_name, ETF_DATA_PATH, start_dt, end_dt, trading_days)
        ind_roi_pool[industry] = roi
        ind_pnl_pool[industry] = pnl

    # Instantiate complete DataFrames instantly
    industry_level1_roi_all_df = pd.DataFrame(ind_roi_pool, index=trading_days)
    industry_level1_pnl_all_df = pd.DataFrame(ind_pnl_pool, index=trading_days)

    # Process Benchmarks (Single-Pass Loop)
    bench_roi_pool = {}
    bench_pnl_pool = {}

    for benchmark in BENCHMARK_List:
        file_name = BENCHMARK_PATH_MAPPING[benchmark]
        roi, pnl = calculate_asset_metrics(file_name, ETF_DATA_PATH, start_dt, end_dt, trading_days)
        bench_roi_pool[benchmark] = roi
        bench_pnl_pool[benchmark] = pnl

    # Instantiate complete DataFrames instantly
    benchmark_roi_all_df = pd.DataFrame(bench_roi_pool, index=trading_days)
    benchmark_pnl_all_df = pd.DataFrame(bench_pnl_pool, index=trading_days)

    # Final Format Touch: Name index columns to match old outputs
    for df in [industry_level1_roi_all_df, industry_level1_pnl_all_df, benchmark_roi_all_df, benchmark_pnl_all_df]:
        df.index.name = "date"
    output['industry_level1_roi_all_df'] = industry_level1_roi_all_df
    output['industry_level1_pnl_all_df'] = industry_level1_pnl_all_df
    output['benchmark_roi_all_df'] = benchmark_roi_all_df
    output['benchmark_pnl_all_df'] = benchmark_pnl_all_df

    return output

def plot_cumulative_returns(portfolio_net_roi, **kwargs):
    """
    We now have:
    1. positions DataFrame: indicates whether we hold each stock on each day (1.0 for hold, 0.0 for not hold).
    2. fee DataFrame: indicates the transaction fee incurred on each stock on each day (0.0 if no transaction, otherwise the fee rate).
    3. weights DataFrame: indicates the weight of each stock in the portfolio on each day (equal weighted among held stocks).
    These DataFrames can be used for backtesting the trading strategy.

    Now we can calculate the daily portfolio returns based on the weights and price returns.
    The daily portfolio return is calculated as the sum of the product of weights and price returns for all stocks.
    """

    HS_300 = kwargs.get('HS_300', pd.Series(dtype=float))
    CS_500 = kwargs.get('CS_500', pd.Series(dtype=float))
    CS_1000 = kwargs.get('CS_1000', pd.Series(dtype=float))
    EW = kwargs.get('EW', pd.Series(dtype=float))
    # Then, plot the cumulative returns of the portfolio and benchmark for comparison.
    cumulative_portfolio_return = (1 + portfolio_net_roi).cumprod()
    cumulative_HS300_return = (1 + HS_300).cumprod()
    cumulative_CS_500_return = (1 + CS_500).cumprod()
    cumulative_CS_1000_return = (1 + CS_1000).cumprod()
    cumulative_EW_return = (1 + EW).cumprod()

    plt.rcParams["axes.unicode_minus"] = False  # Display negative sign correctly
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 5), sharex=True)
    max_equity = max(cumulative_portfolio_return)
    max_equity_date = cumulative_portfolio_return.idxmax().date()
    min_equity = min(cumulative_portfolio_return)
    min_equity_date = cumulative_portfolio_return.idxmin().date()
    ax1.axhline(y=1, color="grey", linestyle="--")
    ax1.plot(cumulative_portfolio_return, label="Equity", color="orange")
    ax1.plot(cumulative_HS300_return.index, cumulative_HS300_return, label='HS 300', color="r")
    ax1.plot(cumulative_CS_500_return.index, cumulative_CS_500_return, label='CS 500', color="g")
    ax1.plot(cumulative_CS_1000_return.index, cumulative_CS_1000_return, label='CS 1000', color="b")
    ax1.plot(cumulative_EW_return.index, cumulative_EW_return, label='Equal-Weighted', color="purple")
    # ax1.set_title(f"Cumulative Returns: Portfolio vs Benchmarks")
    ax1.legend(bbox_to_anchor=(1, 0.5), loc="center left")
    # Annotate max value of equity
    # xy is the point to annotate, xytext is the position of the text
    # --- UPDATED: Annotate max value of equity ---
    ax1.annotate(
        f'Max: {max_equity:.3f} ({max_equity_date})', 
        xy=(cumulative_portfolio_return.idxmax(), max_equity),
        xytext=(cumulative_portfolio_return.idxmax(), 1.05),   # 1.05 sets it exactly at title height
        textcoords=ax1.get_xaxis_transform(),                  # X uses dates, Y uses axis fractions
    #     ha='center',                                           # Centers the text over the arrow
        arrowprops=dict(facecolor='black', arrowstyle='->')
    )

    # --- UPDATED: Annotate min value of equity ---
    ax1.annotate(
        f'Min: {min_equity:.3f} ({min_equity_date})', 
        xy=(cumulative_portfolio_return.idxmin(), min_equity),
        xytext=(cumulative_portfolio_return.idxmin(), -0.15),  # -0.15 sets it slightly below the x-axis
        textcoords=ax1.get_xaxis_transform(),
    #     ha='center',
        arrowprops=dict(facecolor='black', arrowstyle='->')
    )
    rolling_max = cumulative_portfolio_return.cummax()
    drawdown = (cumulative_portfolio_return - rolling_max) / rolling_max
    max_drawdown = min(drawdown)
    max_drawdown_start = drawdown.idxmin().date()

    ax2.plot(drawdown, label="Drawdown", color="maroon")
    # Shade the area where drawdown is negative
    ax2.fill_between(drawdown.index, 
                    drawdown, 
                    0, 
                    where=drawdown < 0, 
                    color='maroon', 
                    alpha=0.3)
    ax2.set_title("Drawdown Curve")
    ax2.legend(bbox_to_anchor=(1, 0.5), loc="center left")
    # Annotate min value of ax2
    # --- UPDATED: Annotate min value of ax2 (Max Drawdown) ---
    ax2.annotate(
        f'Min: {max_drawdown:.3f} ({max_drawdown_start})', 
        xy=(drawdown.idxmin(), max_drawdown),
        xytext=(drawdown.idxmin(), -0.2),                      # Puts text securely at the bottom of the subplot
        textcoords=ax2.get_xaxis_transform(),
    #     ha='center',
        arrowprops=dict(facecolor='black', arrowstyle='->')
    )
    ax1.grid(True)
    ax2.grid(True)
    plt.tight_layout()
    plt.show()

def analyze_factor_performance(signal_df, signal_roi_df, portfolio_net_roi, trading_days, **kwargs):
    """
    Analyze the performance of factors in the portfolio.
    """
    # Ensure we use the proper risk-free rate assumption consistently across metrics
    ANNUAL_RISK_FREE_RATE = 0.03  # 3% standard benchmark
    signal_cumulative_return = (1 + portfolio_net_roi).cumprod()
    # Extract benchmark returns from kwargs
    HS_300 = kwargs.get('HS_300', pd.Series(dtype=float))
    CS_500 = kwargs.get('CS_500', pd.Series(dtype=float))
    CS_1000 = kwargs.get('CS_1000', pd.Series(dtype=float))
    cumulative_HS300_return = (1 + HS_300).cumprod()
    cumulative_CS_500_return = (1 + CS_500).cumprod()
    cumulative_CS_1000_return = (1 + CS_1000).cumprod()
    EW = kwargs.get('EW', pd.Series(dtype=float))
    cumulative_EW_return = (1 + EW).cumprod()
    # =====================================================================
    # 1. FACTOR ANALYSIS ENGINE (IC, RankIC, ICIR, t-value)
    # =====================================================================
    print("\n" + "="*20 + " FACTOR ANALYSIS " + "="*20)

    # Calculate Rank IC using the continuous factor score instead of truncated signals
    IC_Series = signal_df.corrwith(signal_roi_df, axis=1, method="spearman").fillna(0.0)

    IC_mean = IC_Series.mean()
    IC_std = IC_Series.std()
    ICIR = IC_mean / IC_std if IC_std != 0 else 0.0
    # FIXED: t-value multiplies by sqrt(N), does not divide
    t_value = ICIR * np.sqrt(len(IC_Series)) if len(IC_Series) > 0 else 0.0
    IC_winning_rate = sum(1 for ic in IC_Series if ic > 0) / len(IC_Series) if len(IC_Series) > 0 else 0.0

    print(f"IC Mean:          {IC_mean:.4f}")
    print(f"ICIR:             {ICIR:.4f}")
    print(f"IC t-value:       {t_value:.4f}")
    print(f"IC Winning Rate:  {IC_winning_rate:.2%}")

    # Optional: Plot Factor IC Performance
    fig_ic, ax_ic = plt.subplots(figsize=(15, 4))
    ax_ic.bar(IC_Series.index, IC_Series.values, label='Daily RankIC', color='skyblue', alpha=0.7)
    ax_ic_twin = ax_ic.twinx()
    ax_ic_twin.plot(IC_Series.index, IC_Series.cumsum(), color='orange', label='Cumulative IC')
    ax_ic.set_title('Factor RankIC Timeline')
    ax_ic.set_ylabel('RankIC')
    ax_ic_twin.set_ylabel('Cumulative Sum')
    ax_ic.grid(True, linestyle='--', alpha=0.5)
    plt.show()

    # =====================================================================
    # 2. PORTFOLIO PERFORMANCE METRICS (ROI, APY, Sharpe, Alpha, Beta)
    # =====================================================================
    print("\n" + "="*20 + " PERFORMANCE METRICS " + "="*20)

    N_days = len(trading_days)

    # Total Returns (ROI)
    ROI = signal_cumulative_return.iloc[-1] - 1
    HS_300_ROI = cumulative_HS300_return.iloc[-1] - 1
    CS_500_ROI = cumulative_CS_500_return.iloc[-1] - 1
    CS_1000_ROI = cumulative_CS_1000_return.iloc[-1] - 1
    EW_ROI = cumulative_EW_return.iloc[-1] - 1

    # Annualized Returns (APY)
    APY = (signal_cumulative_return.iloc[-1]) ** (252 / N_days) - 1
    HS_300_APY = (cumulative_HS300_return.iloc[-1]) ** (252 / N_days) - 1
    CS_500_APY = (cumulative_CS_500_return.iloc[-1]) ** (252 / N_days) - 1
    CS_1000_APY = (cumulative_CS_1000_return.iloc[-1]) ** (252 / N_days) - 1
    EW_APY = (cumulative_EW_return.iloc[-1]) ** (252 / N_days) - 1

    # Volatility (Annualized)
    Asset_Annual_Volatility = portfolio_net_roi.std() * np.sqrt(252)
    HS_300_Annual_Volatility = HS_300.std() * np.sqrt(252)
    CS_500_Annual_Volatility = CS_500.std() * np.sqrt(252)
    CS_1000_Annual_Volatility = CS_1000.std() * np.sqrt(252)
    EW_Annual_Volatility = EW.std() * np.sqrt(252)

    # Sharpe Ratio (Using Daily Arithmetic Returns for standard institutional representation)
    sharpe_ratio = (portfolio_net_roi.mean() / portfolio_net_roi.std()) * np.sqrt(252) if portfolio_net_roi.std() != 0 else 0.0
    HS_300_sharpe_ratio = (HS_300.mean() / HS_300.std()) * np.sqrt(252) if HS_300.std() != 0 else 0.0
    CS_500_sharpe_ratio = (CS_500.mean() / CS_500.std()) * np.sqrt(252) if CS_500.std() != 0 else 0.0
    CS_1000_sharpe_ratio = (CS_1000.mean() / CS_1000.std()) * np.sqrt(252) if CS_1000.std() != 0 else 0.0
    EW_sharpe_ratio = (EW.mean() / EW.std()) * np.sqrt(252) if EW.std() != 0 else 0.0
    
    # FIXED: Calculate Beta and Alpha using daily ROIs, not cumulative equity paths
    Beta = portfolio_net_roi.cov(HS_300) / HS_300.var() if HS_300.var() != 0 else 1.0
    Alpha = APY - (ANNUAL_RISK_FREE_RATE + Beta * (HS_300_APY - ANNUAL_RISK_FREE_RATE))

    print(f"{'Metric':<20} | {'Portfolio':<10} | {'HS300':<10} | {'CSI500':<10} | {'CSI1000':<10} | {'Equal-Weighted':<15}")
    print("-" * 85)
    print(f"{'Total ROI':<20} | {ROI:.2%} | {HS_300_ROI:.2%} | {CS_500_ROI:.2%} | {CS_1000_ROI:.2%} | {EW_ROI:.2%}")
    print(f"{'Annualized APY':<20} | {APY:.2%} | {HS_300_APY:.2%} | {CS_500_APY:.2%} | {CS_1000_APY:.2%} | {EW_APY:.2%}")
    print(f"{'Annual Volatility':<20} | {Asset_Annual_Volatility:.2%} | {HS_300_Annual_Volatility:.2%} | {CS_500_Annual_Volatility:.2%} | {CS_1000_Annual_Volatility:.2%} | {EW_Annual_Volatility:.2%}")
    print(f"{'Sharpe Ratio':<20} | {sharpe_ratio:.4f} | {HS_300_sharpe_ratio:.4f} | {CS_500_sharpe_ratio:.4f} | {CS_1000_sharpe_ratio:.4f} | {EW_sharpe_ratio:.4f}")
    print("-" * 85)
    print(f"Portfolio Beta (vs HS300): {Beta:.2f}")
    print(f"Portfolio Alpha (Annual):  {Alpha:.2%}")

# Define an index: SoV (Share of Voice)
# SoV_{i, t} = (Number of industry i ads at month t) / (Total number of ads at month t)

# Calculate SoV for each industry and month use "industry_count"
# "industry_count" is like: {"YYYYMMDD": {industry1: count, industry2: count, ...}, ...}
# Some date may be {}, which means there is no ad

def Calculate_SOV(industry_count):
    """
    Calculate Share of Voice (SoV) for each industry by month.
    
    Parameters:
    -----------
    industry_count : dict
        Dictionary in format {"YYYYMMDD": {industry1: count, industry2: count, ...}, ...}
        Some dates may have empty dictionaries (no ads)
    
    Returns:
    --------
    dict
        Dictionary in format {"YYYYMM": {industry1: SoV, industry2: SoV, ...}, ...}
        SoV values are between 0 and 1
    """
    
    # Step 1: Aggregate data by month
    monthly_data = {}
    
    for date_str, day_data in industry_count.items():
        # Extract year and month (first 6 characters)
        month_key = date_str[:6]
        
        # Initialize month entry if it doesn't exist
        if month_key not in monthly_data:
            monthly_data[month_key] = {}
        
        # Sum up counts for each industry for this day
        for industry, count in day_data.items():
            monthly_data[month_key][industry] = monthly_data[month_key].get(industry, 0) + count
    
    # Step 2: Calculate SoV for each month
    sov_results = {}
    
    for month, month_data in monthly_data.items():
        # Calculate total ads for the month
        total_ads = sum(month_data.values())
        
        # Skip months with no ads
        if total_ads == 0:
            sov_results[month] = {}
            continue
        
        # Calculate SoV for each industry
        monthly_sov = {}
        for industry, count in month_data.items():
            monthly_sov[industry] = round(count / total_ads, 3)
        
        sov_results[month] = monthly_sov
    
    return sov_results


# Alternative function that returns the same data but sorted by month
# def calculate_sov_sorted(industry_count):
#     """
#     Calculate Share of Voice (SoV) for each industry by month, sorted chronologically.
#     """
#     sov_results = calculate_sov(industry_count)
    
#     # Sort months chronologically
#     sorted_months = sorted(sov_results.keys())
#     sorted_results = {month: sov_results[month] for month in sorted_months}
    
#     return sorted_results


# # Alternative function that includes all industries even in months where they have 0 ads
# def calculate_sov_complete(industry_count):
#     """
#     Calculate SoV including all industries with 0 for months where they don't appear.
#     """
#     # First, get all unique industries across all months
#     all_industries = set()
#     for day_data in industry_count.values():
#         all_industries.update(day_data.keys())
    
#     # Calculate basic SoV
#     sov_results = calculate_sov(industry_count)
    
#     # Add 0 for missing industries in each month
#     for month_data in sov_results.values():
#         for industry in all_industries:
#             if industry not in month_data:
#                 month_data[industry] = 0.0
    
#     return sov_results

# sov_monthly_data = Calculate_SOV(industry_count)